### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by teresaibarra** [scoopmatic/doc2topic#2]
Hello there!

My team and I are a little new to Keras and we were wondering if we could get a bit of help.
Say we wanted to get the topics for some document not within `patents.txt`. How would we be able to get those?

Thanks!

**Comment by sronnqvist** [comment]
Hi!

At the moment, the code only supports training in batch mode and topics for new documents can't be inferred on the fly. You could, however, train on an initial batch and save the word embeddings, then train a model on new documents with pre-trained and frozen word embeddings (for the new model's embW set weights=inital_model.model.layers[initial_model.layer_lookup['wordvecs']].get_weights() and trainable=False). Hope this solves your problem!

-Samuel

**Comment by teresaibarra** [comment]
Thank you!! I will be trying this out soon. I have another question for you that I'll post in a new issue :)
